### ISSUE TITLE
Issues Accessing Data Structures in space_editor After File Restructure

### ISSUE THREAD

**Issue by Sandvoxel** [rewin123/space_editor#117]
I've been working with the latest version of space_editor, directly from the git repository, because I want to utilize Bevy 0.12 in my project. However, I've encountered an issue that seems to stem from the recent file restructure in the space_editor project.

Issue Description:

Context: I'm using the latest version of space_editor from the git repository.
Problem: Many of the structs that were moved to their own crate are now inaccessible, which is making it difficult to use the project effectively.

Set up a new project with the following dependencies in Cargo.toml:

```toml 
[package]
name = "test-project"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"
space_editor = { git = "https://github.com/rewin123/space_editor.git" }
bevy_xpbd_3d = "0.3.1"
```
